[package]
name = "ch12-fortuner"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
regex = "1.12.2"
rand = "0.10.0-rc.1"
walkdir = "2.5.0"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
