[package]
name = "ch7-findr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
walkdir = "2.5.0"
regex = "1.12.2"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
rand = "0.10.0-rc.0"
tempfile = "3.23.0"
