[package]
name = "ch13-calr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
chrono = "0.4.42"
ansi_term = "0.12.1"
itertools = "0.14.0"

[dev-dependencies]
assert_cmd = "2.1.1"
predicates = "3.1.3"
